name: jdx_mafia

dependencies:
- numpy
- pandas
- jupyterlab
- matplotlib
- seaborn
- scipy
- statsmodels
- pip
- pip: 
  - cvxpy
  - statsmodels
  - plotly
  - joblib
  - cplex
  - docplex
  - gurobipy
  - qpsolvers
  - cvxopt
  - scs
  - osqp
  - ecos

