name: Continuous Integration

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: conda-incubator/setup-miniconda@v2
      with:
           activate-environment: jdx-mafia
           environment-file: environment.yml
           python-version: 3.6
           auto-activate-base: false
    - name: test main notebook
      shell: bash -l {0}
      run: |
        export PATH="$PATH:/usr/share/miniconda/bin"
        conda activate jdx-mafia
        jupyter nbconvert --to html --execute --ExecutePreprocessor.timeout=5000 "Replication notebook.ipynb"
